changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Novas receitas e recursos
      labels:
        - enhancement
    - title: Correções
      labels:
        - bug
    - title: Documentação
      labels:
        - documentation
    - title: Comunidade e manutenção
      labels:
        - "*"
