title: LAB8 Open Source Hub
description: Recursos educacionais abertos de IA, automação e agentes inteligentes.
url: https://lbedu.me
baseurl: ""
lang: pt-BR
theme: jekyll-theme-cayman
show_downloads: false
repository: lbconsultoriadigital/lab8edu.me
